[mobs]
	#Disable all OreSpawn mobs from spawning
	allMobsDisable = false
	mosquitoEnable = true
	rockEnable = true
	ghostEnable = true
	ghostSkellyEnable = true
	spiderDriverEnable = true
	jefferyEnable = true
	mothraEnable = true
	brutalflyEnable = true
	nastysaurusEnable = true
	pointysaurusEnable = true
	cricketEnable = true
	frogEnable = true
	blackAntEnable = true
	redAntEnable = true
	termiteEnable = true
	unstableAntEnable = true
	rainbowAntEnable = true
	alosaurusEnable = true
	hammerheadEnable = true
	leonEnable = true
	caterKillerEnable = true
	molenoidEnable = true
	trexEnable = true
	cryolophosaurusEnable = true
	urchinEnable = true
	camarasaurusEnable = true
	chipmunkEnable = true
	ostrichEnable = true
	gazelleEnable = true
	velocityRaptorEnable = true
	hydroliscEnable = true
	spyroEnable = true
	baryonyxEnable = true
	cockateilEnable = true
	cassowaryEnable = true
	easterBunnyEnable = true
	peacockEnable = true
	kyuubiEnable = true
	cephadromeEnable = true
	dragonEnable = true
	gammaMetroidEnable = true
	basiliskEnable = true
	dragonflyEnable = true
	mothraPeaceful = false

[tweaks]
	lessOre = false
	# Default: 0
	# Range: 0 ~ 2
	lessLag = 0
	ratPlayerFriendly = true
	ratPetFriendly = true
	# Default: 0
	# Range: 0 ~ 5
	nightmareSize = 0
	# Default: 2
	# Range: 1 ~ 5
	islandSpeedFactor = 2
	# Default: 2
	# Range: 1 ~ 5
	islandSizeFactor = 2
	ginormousEmeraldTreeEnable = true
	guiOverlayEnable = true
	ultimateSwordPvp = false
	bigBerthaPvp = false
	boyfriendBroMode = false
	duplicatorTreeEnable = true
	royalGlideEnable = true
	dragonflyHorseFriendly = false
	playNicely = false
	minersDreamExpensive = false
	disableOverworldDungeons = false
	fullPowerKingEnable = false

[weapons]
	# Default: 5
	# Range: 1 ~ 10
	ultimateSwordEnchantmentLevel = 5
	# Default: 10
	# Range: 2 ~ 20
	ultimateBowDamage = 10
