/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.entity.EntityList
 *  net.minecraft.entity.monster.EntityCreeper
 *  net.minecraft.entity.monster.EntityGhast
 *  net.minecraft.entity.monster.EntityZombie
 *  net.minecraft.entity.passive.EntityCow
 *  net.minecraft.entity.passive.EntityHorse
 *  net.minecraft.entity.passive.EntityPig
 *  net.minecraft.init.Blocks
 *  net.minecraft.init.Items
 *  net.minecraft.item.ItemMonsterPlacer
 *  net.minecraft.item.ItemStack
 *  net.minecraft.item.crafting.Ingredient
 *  net.minecraft.util.ResourceLocation
 *  net.minecraftforge.fml.common.registry.GameRegistry
 */
package danger.orespawn.recipes;

import danger.orespawn.init.ModBlocks;
import danger.orespawn.init.ModItems;
import java.util.Objects;
import net.minecraft.entity.EntityList;
import net.minecraft.entity.monster.EntityCreeper;
import net.minecraft.entity.monster.EntityGhast;
import net.minecraft.entity.monster.EntityZombie;
import net.minecraft.entity.passive.EntityCow;
import net.minecraft.entity.passive.EntityHorse;
import net.minecraft.entity.passive.EntityPig;
import net.minecraft.init.Blocks;
import net.minecraft.init.Items;
import net.minecraft.item.ItemMonsterPlacer;
import net.minecraft.item.ItemStack;
import net.minecraft.item.crafting.Ingredient;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.registry.GameRegistry;

public class CraftingRecipes {
    public static void init() {
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("uranium_ingot"), null, (ItemStack)new ItemStack(ModItems.URANIUM_INGOT, 9), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.URANIUM_BLOCK)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("titanium_ingot"), null, (ItemStack)new ItemStack(ModItems.TITANIUM_INGOT, 9), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.TITANIUM_BLOCK)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("uranium_nugget"), null, (ItemStack)new ItemStack(ModItems.URANIUM_NUGGET, 9), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModItems.URANIUM_INGOT)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("titanium_nugget"), null, (ItemStack)new ItemStack(ModItems.TITANIUM_NUGGET, 9), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModItems.TITANIUM_INGOT)})});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("ultimate_sword"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.ULTIMATE_SWORD, 1), (Object[])new Object[]{"XTX", "XUX", "XIX", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('I'), Items.field_151042_j, Character.valueOf('U'), ModItems.URANIUM_INGOT, Character.valueOf('T'), ModItems.TITANIUM_INGOT});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("ultimate_pickaxe"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.ULTIMATE_PICKAXE, 1), (Object[])new Object[]{"TUT", "XUX", "XIX", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('I'), Items.field_151042_j, Character.valueOf('U'), ModItems.URANIUM_INGOT, Character.valueOf('T'), ModItems.TITANIUM_INGOT});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("ultimate_axe"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.ULTIMATE_AXE, 1), (Object[])new Object[]{"TUX", "TIX", "XIX", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('I'), Items.field_151042_j, Character.valueOf('U'), ModItems.URANIUM_INGOT, Character.valueOf('T'), ModItems.TITANIUM_INGOT});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("ultimate_shovel"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.ULTIMATE_SHOVEL, 1), (Object[])new Object[]{"XUX", "XTX", "XIX", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('I'), Items.field_151042_j, Character.valueOf('U'), ModItems.URANIUM_INGOT, Character.valueOf('T'), ModItems.TITANIUM_INGOT});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("ultimate_hoe"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.ULTIMATE_HOE, 1), (Object[])new Object[]{"TUX", "XIX", "XIX", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('I'), Items.field_151042_j, Character.valueOf('U'), ModItems.URANIUM_INGOT, Character.valueOf('T'), ModItems.TITANIUM_INGOT});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("ultimate_helmet"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.ULTIMATE_HELMET, 1), (Object[])new Object[]{"XXX", "TIT", "UXU", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('I'), Items.field_151042_j, Character.valueOf('U'), ModItems.URANIUM_INGOT, Character.valueOf('T'), ModItems.TITANIUM_INGOT});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("ultimate_chestplate"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.ULTIMATE_CHESTPLATE, 1), (Object[])new Object[]{"IXI", "TTT", "UUU", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('I'), Items.field_151042_j, Character.valueOf('U'), ModItems.URANIUM_INGOT, Character.valueOf('T'), ModItems.TITANIUM_INGOT});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("ultimate_leggings"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.ULTIMATE_LEGGINGS, 1), (Object[])new Object[]{"III", "TXT", "UXU", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('I'), Items.field_151042_j, Character.valueOf('U'), ModItems.URANIUM_INGOT, Character.valueOf('T'), ModItems.TITANIUM_INGOT});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("ultimate_boots"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.ULTIMATE_BOOTS, 1), (Object[])new Object[]{"XXX", "TXT", "UXU", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('U'), ModItems.URANIUM_INGOT, Character.valueOf('T'), ModItems.TITANIUM_INGOT});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("emerald_sword"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.EMERALD_SWORD, 1), (Object[])new Object[]{"XYX", "XYX", "XZX", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), Items.field_151166_bC, Character.valueOf('Z'), Items.field_151055_y});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("emerald_pickaxe"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.EMERALD_PICKAXE, 1), (Object[])new Object[]{"YYY", "XZX", "XZX", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), Items.field_151166_bC, Character.valueOf('Z'), Items.field_151055_y});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("emerald_axe"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.EMERALD_AXE, 1), (Object[])new Object[]{"YYX", "YZX", "XZX", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), Items.field_151166_bC, Character.valueOf('Z'), Items.field_151055_y});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("emerald_shovel"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.EMERALD_SHOVEL, 1), (Object[])new Object[]{"XYX", "XZX", "XZX", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), Items.field_151166_bC, Character.valueOf('Z'), Items.field_151055_y});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("emerald_hoe"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.EMERALD_HOE, 1), (Object[])new Object[]{"YYX", "XZX", "XZX", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), Items.field_151166_bC, Character.valueOf('Z'), Items.field_151055_y});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("emerald_helmet"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.EMERALD_HELMET, 1), (Object[])new Object[]{"XXX", "YYY", "YXY", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), Items.field_151166_bC});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("emerald_chestplate"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.EMERALD_CHESTPLATE, 1), (Object[])new Object[]{"YXY", "YYY", "YYY", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), Items.field_151166_bC});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("emerald_leggings"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.EMERALD_LEGGINGS, 1), (Object[])new Object[]{"YYY", "YXY", "YXY", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), Items.field_151166_bC});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("emerald_boots"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.EMERALD_BOOTS, 1), (Object[])new Object[]{"XXX", "YXY", "YXY", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), Items.field_151166_bC});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("empty_cage"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.EMPTY_CAGE, 2), (Object[])new Object[]{"ISI", "SXS", "ISI", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('S'), Items.field_151055_y, Character.valueOf('I'), Items.field_151042_j});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("alosaurus_egg"), null, (ItemStack)new ItemStack(ModItems.ALOSAURUS_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.ALOSAURUS_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("baryonyx_egg"), null, (ItemStack)new ItemStack(ModItems.BARYONYX_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.BARYONYX_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("camarasaurus_egg"), null, (ItemStack)new ItemStack(ModItems.CAMARASAURUS_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.CAMARASAURUS_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("cryolophosaurus_egg"), null, (ItemStack)new ItemStack(ModItems.CRYOLOPHOSAURUS_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.CRYOLOPHOSAURUS_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("pointysaurus_egg"), null, (ItemStack)new ItemStack(ModItems.POINTYSAURUS_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.POINTYSAURUS_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("trex_egg"), null, (ItemStack)new ItemStack(ModItems.TREX_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.TREX_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("bird_egg"), null, (ItemStack)new ItemStack(ModItems.BIRD_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.BIRD_ORE)})});
        ItemStack cowEgg = new ItemStack(Items.field_151063_bx, 1);
        ItemMonsterPlacer.func_185078_a((ItemStack)cowEgg, (ResourceLocation)Objects.requireNonNull(EntityList.func_191306_a(EntityCow.class)));
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("cow_egg"), null, (ItemStack)cowEgg, (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.COW_ORE)})});
        ItemStack creeperEgg = new ItemStack(Items.field_151063_bx, 1);
        ItemMonsterPlacer.func_185078_a((ItemStack)creeperEgg, (ResourceLocation)Objects.requireNonNull(EntityList.func_191306_a(EntityCreeper.class)));
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("creeper_egg"), null, (ItemStack)creeperEgg, (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.CREEPER_ORE)})});
        ItemStack ghastEgg = new ItemStack(Items.field_151063_bx, 1);
        ItemMonsterPlacer.func_185078_a((ItemStack)ghastEgg, (ResourceLocation)Objects.requireNonNull(EntityList.func_191306_a(EntityGhast.class)));
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("ghast_egg"), null, (ItemStack)ghastEgg, (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.GHAST_ORE)})});
        ItemStack horseEgg = new ItemStack(Items.field_151063_bx, 1);
        ItemMonsterPlacer.func_185078_a((ItemStack)horseEgg, (ResourceLocation)Objects.requireNonNull(EntityList.func_191306_a(EntityHorse.class)));
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("horse_egg"), null, (ItemStack)horseEgg, (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.HORSE_ORE)})});
        ItemStack pigEgg = new ItemStack(Items.field_151063_bx, 1);
        ItemMonsterPlacer.func_185078_a((ItemStack)pigEgg, (ResourceLocation)Objects.requireNonNull(EntityList.func_191306_a(EntityPig.class)));
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("pig_egg"), null, (ItemStack)pigEgg, (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.PIG_ORE)})});
        ItemStack zombieEgg = new ItemStack(Items.field_151063_bx, 1);
        ItemMonsterPlacer.func_185078_a((ItemStack)cowEgg, (ResourceLocation)Objects.requireNonNull(EntityList.func_191306_a(EntityZombie.class)));
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("zombie_egg"), null, (ItemStack)zombieEgg, (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.ZOMBIE_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("alien_egg"), null, (ItemStack)new ItemStack(ModItems.ALIEN_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.ALIEN_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("cavefisher_egg"), null, (ItemStack)new ItemStack(ModItems.CAVEFISHER_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.CAVEFISHER_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("nastysaurus_egg"), null, (ItemStack)new ItemStack(ModItems.NASTYSAURUS_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.NASTYSAURUS_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("velocityraptor_egg"), null, (ItemStack)new ItemStack(ModItems.VELOCITYRAPTOR_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.VELOCITYRAPTOR_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("gammametroid_egg"), null, (ItemStack)new ItemStack(ModItems.GAMMAMETROID_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.WTF_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("spyro_egg"), null, (ItemStack)new ItemStack(ModItems.SPYRO_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.SPYRO_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("dragonfly_egg"), null, (ItemStack)new ItemStack(ModItems.DRAGONFLY_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.DRAGONFLY_ORE)})});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("moth_helmet"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.MOTH_HELMET, 1), (Object[])new Object[]{"XXX", "YYY", "YXY", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), ModItems.MOTH_SCALE});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("moth_chestplate"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.MOTH_CHESTPLATE, 1), (Object[])new Object[]{"YXY", "YYY", "YYY", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), ModItems.MOTH_SCALE});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("moth_leggings"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.MOTH_LEGGINGS, 1), (Object[])new Object[]{"YYY", "YXY", "YXY", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), ModItems.MOTH_SCALE});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("moth_boots"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.MOTH_BOOTS, 1), (Object[])new Object[]{"XXX", "YXY", "YXY", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), ModItems.MOTH_SCALE});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("worm_food"), null, (ItemStack)new ItemStack(ModItems.WORM_FOOD, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Blocks.field_150346_d, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151115_aP)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("kyuubi_egg"), null, (ItemStack)new ItemStack(ModItems.KYUUBI_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.KYUUBI_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("beaver_egg"), null, (ItemStack)new ItemStack(ModItems.BEAVER_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.BEAVER_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("brutalfly_egg"), null, (ItemStack)new ItemStack(ModItems.BRUTALFLY_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.BRUTALFLY_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("mothra_egg"), null, (ItemStack)new ItemStack(ModItems.MONTHRA_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.MOTHRA_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("mantis_egg"), null, (ItemStack)new ItemStack(ModItems.MANTIS_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.MANTIS_ORE)})});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("amethyst_sword"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.AMETHYST_SWORD, 1), (Object[])new Object[]{"XYX", "XYX", "XZX", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), ModItems.AMETHYST, Character.valueOf('Z'), Items.field_151055_y});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("amethyst_axe"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.AMETHYST_AXE, 1), (Object[])new Object[]{"YYX", "YZX", "XZX", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), ModItems.AMETHYST, Character.valueOf('Z'), Items.field_151055_y});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("amethyst_pickaxe"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.AMETHYST_PICKAXE, 1), (Object[])new Object[]{"YYY", "XZX", "XZX", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), ModItems.AMETHYST, Character.valueOf('Z'), Items.field_151055_y});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("amethyst_hoe"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.AMETHYST_HOE, 1), (Object[])new Object[]{"YYX", "XZX", "XZX", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), ModItems.AMETHYST, Character.valueOf('Z'), Items.field_151055_y});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("amethyst_helmet"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.AMETHYST_HELMET, 1), (Object[])new Object[]{"XXX", "YYY", "YXY", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), ModItems.AMETHYST});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("amethyst_chestplate"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.AMETHYST_CHESTPLATE, 1), (Object[])new Object[]{"YXY", "YYY", "YYY", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), ModItems.AMETHYST});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("amethyst_leggings"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.AMETHYST_LEGGINGS, 1), (Object[])new Object[]{"YYY", "YXY", "YXY", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), ModItems.AMETHYST});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("amethyst_boots"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModItems.AMETHYST_BOOTS, 1), (Object[])new Object[]{"XXX", "YXY", "YXY", Character.valueOf('X'), Blocks.field_150350_a, Character.valueOf('Y'), ModItems.AMETHYST});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("cassowary_egg"), null, (ItemStack)new ItemStack(ModItems.CASSOWARY_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.CASSOWARY_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("redcow_egg"), null, (ItemStack)new ItemStack(ModItems.REDCOW_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.REDCOW_ORE)})});
        GameRegistry.addShapelessRecipe((ResourceLocation)new ResourceLocation("stinkbug_egg"), null, (ItemStack)new ItemStack(ModItems.STINKBUG_EGG, 1), (Ingredient[])new Ingredient[]{Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(Items.field_151131_as, 1)}), Ingredient.func_193369_a((ItemStack[])new ItemStack[]{new ItemStack(ModBlocks.STINKBUG_ORE)})});
        GameRegistry.addShapedRecipe((ResourceLocation)new ResourceLocation("amethyst_block"), (ResourceLocation)new ResourceLocation("orespawn"), (ItemStack)new ItemStack(ModBlocks.AMETHYST_BLOCK, 1), (Object[])new Object[]{"XXX", "XXX", "XXX", Character.valueOf('X'), ModItems.AMETHYST});
    }
}

